// Minimal starter scaffold (autogenerated layout) — copy this folder to begin a new sketch.

function setup() {
  createCanvas(400, 400);
  // Accessibility: text description of the canvas for screen readers
  // https://p5js.org/reference/p5/describe/
  describe("A blank gray canvas; replace this description with one that describes your sketch.");
}

function draw() {
  background(220);
}
